### ISSUE TITLE
Error: Invalid Community Edition license

### ISSUE THREAD

**Issue by mwaseem75** [intersystems-community/iris-dataset-titanic#2]
Hi,
I am getting below error while using docker compose up command:

#11 2.547 Error: Invalid Community Edition license, may have exceeded core limit. - Shutting down the system 
: $zu(56,2)= 0Starting IRIS

Thanks

**Comment by janaka44** [comment]
I'm still getting the same error, what is the solution for this? 
I'm on Windows 11

log:
Startup of InterSystems IRIS [IRIS for Windows (x86-64) 2022.1 (Build 209U) Tue May 31 2022 12:21:28 EDT]
	in c:\intersystems\irishealth\bin\
	with mgr: c:\intersystems\irishealth\mgr
	with wij: c:\intersystems\irishealth\mgr\IRIS.WIJ
	from: c:\intersystems\irishealth\mgr\
  OS=[NT], version=[6.2.9200], 16 processors.
  Processor architecture=[9], level=[6], revision=[9a03], active processor mask=[ffff].
